extend type Mutation {
    login(input: LoginUserInput!): AuthType!
    register(input: RegisterUserInput!): AuthType!
    refresh(input: RefreshAuthenticationInput!): AuthType!
    logout(input: LogoutInput!): Boolean!
}

type AuthType {
    accessToken: String!
    refreshToken: String!
    userId: UserId!
    accountId: AccountId!
}

input LoginUserInput {
    email: String!
    password: String!
}

input LogoutInput {
    refreshToken: String!
}

input RefreshAuthenticationInput {
    refreshToken: String!
}

input RegisterUserInput {
    name: String!
    email: String!
    password: String!
}