spring.application.name=task-management-backend
spring.config.import=optional:file:.env[.properties]
## Database
spring.datasource.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/taskmanagement}
spring.datasource.username=${APP_DB_USERNAME:admin}
spring.datasource.password=${APP_DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## CORS
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS:*}
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS:false}
## JWT
security.jwt.access-token.secret=${APP_JWT_ACCESS_TOKEN_SECRET}
security.jwt.access-token.expiration=${APP_JWT_ACCESS_TOKEN_EXPIRATION}
security.jwt.refresh-token.secret=${APP_JWT_REFRESH_TOKEN_SECRET}
security.jwt.refresh-token.expiration=${APP_JWT_REFRESH_TOKEN_EXPIRATION}
