spring.application.name=task-management-backend
spring.config.import=optional:file:.env[.properties]
## Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS:*}
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS:false}
## JWT
security.jwt.access-token.secret=29f1a2876dd2ff862625aa84df26d16ac13f4c73de73467e6092cf97536ebdc8
security.jwt.access-token.expiration=900000
security.jwt.refresh-token.secret=65bee930dd4ac6288a098009a9a5bac6b9093f18cb79d808c10b0eacd3313d2b
security.jwt.refresh-token.expiration=604800000
