extend type Query {
    getMembers: AccountMemberWithInvitationType
    getUserAccounts: [AccountType]
}

extend type Mutation {
    editAccountMemberRole(userId: UserId, role: Role): AccountMemberType
    removeAccountMember(userId: UserId): Boolean!
    switchAccount(toAccountId: AccountId): AuthType
}

type AccountType {
    id: AccountId!
    name: String!
}

type AccountMemberType {
    id: AccountMemberId!
    user: UserType
    account: AccountType
    role: Role
}

type AccountMemberWithInvitationType {
    accountName: String!
    members: [AccountMemberType]
    openInvitations: [InvitationType]
}

enum Role {
    Admin,
    User
}