extend type Query {
    boards(projectId: ProjectId!): [BoardType!]!
    board(id: BoardId!): BoardType!
}

extend type Mutation {
    createBoard(input: CreateBoardInput!): BoardType!
    editBoard(input: EditBoardInput!): BoardType!
    deleteBoard(boardId: BoardId!): Boolean!
    createBoardSection(input: CreateBoardSectionInput!): BoardSectionType!
    deleteBoardSection(sectionId: BoardSectionId!): Boolean!
    renameBoardSection(sectionId: BoardSectionId!, name: String!): BoardSectionType!
}

type BoardType {
    id: BoardId!
    name: String!
    ownerId: UserId!
    projectId: ProjectId!
    sections: [BoardSectionType!]!
    members: [BoardMemberType!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type BoardMemberType {
    id: BoardMemberId!
    user: UserType!
    joinedAt: DateTime!
}

type BoardSectionType {
    id: BoardSectionId!
    name: String!
    position: Int!
}

input CreateBoardInput {
    projectId: ProjectId!
    name: String!
    sections: [String!]!
    memberIds: [UserId!]
}

input EditBoardInput {
    boardId: BoardId!
    name: String!
    memberIds: [UserId!]
}

input CreateBoardSectionInput {
    boardId: BoardId!
    name: String!
    position: Int
}
