extend type Query {
    projects: [ProjectType!]!
}

extend type Mutation {
    createProject(input: CreateProjectInput!): ProjectType!
    editProject(input: EditProjectInput!): ProjectType!
    deleteProject(projectId: ProjectId!): Boolean!
}

type ProjectType {
    id: ProjectId!
    name: String!
    description: String
    icon: String
    members: [ProjectMemberType!]!
    boards: [BoardType!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type ProjectMemberType {
    id: ProjectMemberId!
    user: UserType!
    joinedAt: DateTime!
}

input CreateProjectInput {
    name: String!
    description: String
    icon: String
    memberIds: [UserId!]
}

input EditProjectInput {
    projectId: ProjectId!
    name: String!
    description: String
    icon: String
    memberIds: [UserId!]
}
